spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
      mail.smtp.starttls.required: false

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /docs
    urls:
      - name: identity
        url: /v3/api-docs

logging:
  level:
    com.template.identity: DEBUG
    org.springframework.security: DEBUG
    org.flywaydb: DEBUG

app:
  jwt:
    secret: ${JWT_SECRET:dev-secret-key-at-least-32-characters-long-ok}
